const countryData = {
    AFG: { name: 'Afghanistan', code: 93 },
    AGO: { name: 'Angola', code: 244 },
    ALB: { name: 'Albania', code: 355 },
    ARE: { name: 'United Arab Emirates', code: 971 },
    ARG: { name: 'Argentina', code: 54 },
    ARM: { name: 'Armenia', code: 374 },
    AUS: { name: 'Australia', code: 61 },
    AUT: { name: 'Austria', code: 43 },
    AZE: { name: 'Azerbaijan', code: 994 },
    BDI: { name: 'Burundi', code: 257 },
    BEL: { name: 'Belgium', code: 32 },
    BFA: { name: 'Burkina Faso', code: 226 },
    BGD: { name: 'Bangladesh', code: 880 },
    BGR: { name: 'Bulgaria', code: 359 },
    BHS: { name: 'The Bahamas', code: 1242 },
    BIH: { name: 'Bosnia and Herzegovina', code: 387 },
    BLR: { name: 'Belarus', code: 375 },
    BOL: { name: 'Bolivia', code: 591 },
    BRA: { name: 'Brazil', code: 55 },
    BRN: { name: 'Brunei', code: 673 },
    BTN: { name: 'Bhutan', code: 975 },
    BWA: { name: 'Botswana', code: 267 },
    CAF: { name: 'Central African Republic', code: 236 },
    CAN: { name: 'Canada', code: 1 },
    CHE: { name: 'Switzerland', code: 41 },
    CHL: { name: 'Chile', code: 56 },
    CHN: { name: 'China', code: 86 },
    CIV: { name: "Côte d'Ivoire", code: 225 },
    CMR: { name: 'Cameroon', code: 237 },
    COD: { name: 'Democratic Republic of the Congo', code: 243 },
    COG: { name: 'Republic of the Congo', code: 242 },
    COL: { name: 'Colombia', code: 57 },
    CRI: { name: 'Costa Rica', code: 506 },
    CUB: { name: 'Cuba', code: 53 },
    CZE: { name: 'Czech Republic', code: 420 },
    DEU: { name: 'Germany', code: 49 },
    DNK: { name: 'Denmark', code: 45 },
    DOM: { name: 'Dominican Republic', code: 1809 },
    DZA: { name: 'Algeria', code: 213 },
    ECU: { name: 'Ecuador', code: 593 },
    EGY: { name: 'Egypt', code: 20 },
    ERI: { name: 'Eritrea', code: 291 },
    ESP: { name: 'Spain', code: 34 },
    EST: { name: 'Estonia', code: 372 },
    ETH: { name: 'Ethiopia', code: 251 },
    FIN: { name: 'Finland', code: 358 },
    FRA: { name: 'France', code: 33 },
    GAB: { name: 'Gabon', code: 241 },
    GBR: { name: 'United Kingdom', code: 44 },
    GEO: { name: 'Georgia', code: 995 },
    GHA: { name: 'Ghana', code: 233 },
    GIN: { name: 'Guinea', code: 224 },
    GMB: { name: 'Gambia', code: 220 },
    GRC: { name: 'Greece', code: 30 },
    GTM: { name: 'Guatemala', code: 502 },
    GUY: { name: 'Guyana', code: 592 },
    HND: { name: 'Honduras', code: 504 },
    HRV: { name: 'Croatia', code: 385 },
    HTI: { name: 'Haiti', code: 509 },
    HUN: { name: 'Hungary', code: 36 },
    IDN: { name: 'Indonesia', code: 62 },
    IND: { name: 'India', code: 91 },
    IRL: { name: 'Ireland', code: 353 },
    IRN: { name: 'Iran', code: 98 },
    IRQ: { name: 'Iraq', code: 964 },
    ISL: { name: 'Iceland', code: 354 },
    ISR: { name: 'Israel', code: 972 },
    ITA: { name: 'Italy', code: 39 },
    JAM: { name: 'Jamaica', code: 1876 },
    JOR: { name: 'Jordan', code: 962 },
    JPN: { name: 'Japan', code: 81 },
    KAZ: { name: 'Kazakhstan', code: 7 },
    KEN: { name: 'Kenya', code: 254 },
    KGZ: { name: 'Kyrgyzstan', code: 996 },
    KHM: { name: 'Cambodia', code: 855 },
    KOR: { name: 'South Korea', code: 82 },
    KWT: { name: 'Kuwait', code: 965 },
    LAO: { name: 'Laos', code: 856 },
    LBN: { name: 'Lebanon', code: 961 },
    LBR: { name: 'Liberia', code: 231 },
    LBY: { name: 'Libya', code: 218 },
    LKA: { name: 'Sri Lanka', code: 94 },
    LSO: { name: 'Lesotho', code: 266 },
    LTU: { name: 'Lithuania', code: 370 },
    LUX: { name: 'Luxembourg', code: 352 },
    LVA: { name: 'Latvia', code: 371 },
    MAR: { name: 'Morocco', code: 212 },
    MDA: { name: 'Moldova', code: 373 },
    MDG: { name: 'Madagascar', code: 261 },
    MEX: { name: 'Mexico', code: 52 },
    MKD: { name: 'Macedonia', code: 389 },
    MLI: { name: 'Mali', code: 223 },
    MMR: { name: 'Myanmar', code: 95 },
    MNE: { name: 'Montenegro', code: 382 },
    MNG: { name: 'Mongolia', code: 976 },
    MOZ: { name: 'Mozambique', code: 258 },
    MRT: { name: 'Mauritania', code: 222 },
    MWI: { name: 'Malawi', code: 265 },
    MYS: { name: 'Malaysia', code: 60 },
    NAM: { name: 'Namibia', code: 264 },
    NER: { name: 'Niger', code: 227 },
    NGA: { name: 'Nigeria', code: 234 },
    NIC: { name: 'Nicaragua', code: 505 },
    NLD: { name: 'Netherlands', code: 31 },
    NOR: { name: 'Norway', code: 47 },
    NPL: { name: 'Nepal', code: 977 },
    NZL: { name: 'New Zealand', code: 64 },
    OMN: { name: 'Oman', code: 968 },
    PAK: { name: 'Pakistan', code: 92 },
    PAN: { name: 'Panama', code: 507 },
    PER: { name: 'Peru', code: 51 },
    PHL: { name: 'Philippines', code: 63 },
    PNG: { name: 'Papua New Guinea', code: 675 },
    POL: { name: 'Poland', code: 48 },
    PRI: { name: 'Puerto Rico', code: 1787 },
    PRK: { name: 'North Korea', code: 850 },
    PRT: { name: 'Portugal', code: 351 },
    PRY: { name: 'Paraguay', code: 595 },
    QAT: { name: 'Qatar', code: 974 },
    ROU: { name: 'Romania', code: 40 },
    RUS: { name: 'Russia', code: 7 },
    RWA: { name: 'Rwanda', code: 250 },
    SAU: { name: 'Saudi Arabia', code: 966 },
    SDN: { name: 'Sudan', code: 249 },
    SEN: { name: 'Senegal', code: 221 },
    SLB: { name: 'Solomon Islands', code: 677 },
    SLE: { name: 'Sierra Leone', code: 232 },
    SLV: { name: 'El Salvador', code: 503 },
    SOM: { name: 'Somalia', code: 252 },
    SRB: { name: 'Serbia', code: 381 },
    SSD: { name: 'South Sudan', code: 211 },
    SVK: { name: 'Slovakia', code: 421 },
    SVN: { name: 'Slovenia', code: 386 },
    SWE: { name: 'Sweden', code: 46 },
    SWZ: { name: 'Swaziland', code: 268 },
    SYR: { name: 'Syria', code: 963 },
    TCD: { name: 'Chad', code: 235 },
    TGO: { name: 'Togo', code: 228 },
    THA: { name: 'Thailand', code: 66 },
    TJK: { name: 'Tajikistan', code: 992 },
    TKM: { name: 'Turkmenistan', code: 993 },
    TLS: { name: 'East Timor', code: 670 },
    TTO: { name: 'Trinidad and Tobago', code: 1868 },
    TUN: { name: 'Tunisia', code: 216 },
    TUR: { name: 'Turkey', code: 90 },
    TWN: { name: 'Taiwan', code: 886 },
    TZA: { name: 'Tanzania', code: 255 },
    UGA: { name: 'Uganda', code: 256 },
    UKR: { name: 'Ukraine', code: 380 },
    URY: { name: 'Uruguay', code: 598 },
    USA: { name: 'United States', code: 1 },
    UZB: { name: 'Uzbekistan', code: 998 },
    VEN: { name: 'Venezuela', code: 58 },
    VNM: { name: 'Vietnam', code: 84 },
    VUT: { name: 'Vanuatu', code: 678 },
    YEM: { name: 'Yemen', code: 967 },
    ZAF: { name: 'South Africa', code: 27 },
    ZMB: { name: 'Zambia', code: 260 },
    ZWE: { name: 'Zimbabwe', code: 263 },
    
    // North American regions
    '11': { name: 'Eastern Canada', code: 11 },
    '12': { name: 'Western Canada', code: 12 },
    '13': { name: 'Western United States', code: 13 },
    '14': { name: 'Midwestern United States', code: 14 },
    '15': { name: 'Eastern United States', code: 15 }
};

export function getCountryName(code) {
    return countryData[code]?.name || 'Unknown Country';
}

export function getCountryPhoneCode(code) {
    return countryData[code]?.code || null;
} 